spring:
  port: 8120
  resources:
    static-locations: file:./index/, file:./static/,/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/, classpath:/public/
  redis:
#    host: 122.112.140.191
    host: 127.0.0.1
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 10
#    password: 5XaMKsTZD5XNpTWC   # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    port: 6379
    lettuce:
      pool:
        max-active: 1024
#    password: nonghai131
#    timeout: 20s
  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/jetlinks
#    username: postgres
#    password: jetlinks

    url: r2dbc:mysql://localhost:3306/jsiot
    username: jsiot
    password: BS2BkXhWGrHCBHyy

#    url: r2dbc:h2:file:///./data/h2db/jetlinks
#    password: jetlinks
    pool:
      max-size: 32
easyorm:
  default-schema: jsiot # 数据库默认的schema,修改数据库时这里也要修改
  dialect: mysql #数据库方言
#  default-schema: public # 数据库默认的schema,修改数据库时这里也要修改
#  dialect: postgres #数据库方言
elasticsearch:
  embedded:
    enabled: true # 为true时使用内嵌的elasticsearch,不建议在生产环境中使用
    data-path: ./data/elasticsearch # 数据目录
    port: 9200
    host: 0.0.0.0
  client:
    host: localhost
    port: 9200
    max-conn-total: 128
    connect-timeout: 5000
    socket-timeout: 5000
    connection-request-timeout: 8000
  index:
    default-strategy: time-by-month #默认es的索引按月进行分表, direct则为直接操作索引.
    settings:
      number-of-shards: 1 # es 分片数量
      number-of-replicas: 0 # 副本数量
logging:
  level:
    com.github.tonivade: error