version: "2"
services:
   influxdb:
      image: influxdb
      ports:
        - "8083:8083"
        - "8086:8086"
        - "8090:8090"
        - "8099:8099"
      environment:
        TZ: Asia/Shanghai
        INFLUXDB_DB: jetlinks